### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by felipegs** [strongloop/node-foreman#107]
Hi,
When 2.0 version will be available on npm repositories?

**Comment by rmg** [comment]
@felipegs there is a prerelease of 2.0 available on npm as the `next` tag. If you are curious to try it, you just need to specify the tag `npm i -g foreman@next`.

**Comment by rmg** [comment]
Now up to [v2.0.0-1](https://github.com/strongloop/node-foreman/releases/tag/v2.0.0-1) under the `next` tag.

@dickeyxxx I'm thinking of releasing a 2.0.0 final once node v6 works (#111, #116). What do you think?

**Comment by Darkhogg** [comment]
How is this going? I've been using 2.0 in productios for a while with no problems, I think it's time...

**Comment by dickeyxxx** [comment]
we use 2.0 for heroku local, I definitely think it's ready

**Comment by rmg** [comment]
Thanks for weighing in. I've just released [2.0.0](https://github.com/strongloop/node-foreman/releases/tag/v2.0.0). 🎉
