### ISSUE TITLE
Does not support node v6

### ISSUE THREAD

**Issue by rmg** [strongloop/node-foreman#111]
Need to change template engines since mu2 makes use of some `Buffer` methods that were deprecated in node 5.x and have been removed in node 6.0.0.

**Comment by dickeyxxx** [comment]
:/ dang, we wanted to move the Heroku CLI to node 6 too, guess this is going to block that

**Comment by rmg** [comment]
Fortunately CI is looking much better now, so hopefully that gives us a more solid foundation for swapping out the template engine.

@dickeyxxx do you have any thoughts on which template engine to switch to? I usually go with lodash's, since it's similar to ejs which is similar to erb.. but that would require rewriting all the templates.

**Comment by dickeyxxx** [comment]
what do we use a template engine for? I guess I need to check the code more

**Comment by rmg** [comment]
The system service configs are generated from templates by `nf export`.
