### ISSUE TITLE
Ctrl + C Does Not Stop Node Express Server Started with Foreman in Windows

### ISSUE THREAD

**Issue by joelcdoyle** [strongloop/node-foreman#118]
When I fire up a local express server in Windows 7 (git bash shell) using node-foreman(1.4.1), along with other processes like `grunt watch` (`nf start web,watch`) I am unable able to kill the server with `Ctrl + C`.

I've verified it's still running by trying to start it again with node-foreman(`nf start web`) and receiving this error: 

```
3:29:34 PM web.1 |  events.js:141
3:29:34 PM web.1 |        throw er; // Unhandled 'error' event
3:29:34 PM web.1 |        ^
3:29:34 PM web.1 |  Error: listen EADDRINUSE :::3000
3:29:34 PM web.1 |      at Object.exports._errnoException (util.js:870:11)
3:29:34 PM web.1 |      at exports._exceptionWithHostPort (util.js:893:20)
3:29:34 PM web.1 |      at Server._listen2 (net.js:1234:14)
3:29:34 PM web.1 |      at listen (net.js:1270:10)
3:29:34 PM web.1 |      at Server.listen (net.js:1366:5)
3:29:34 PM web.1 |      at EventEmitter.listen (C:\Users\jdoyle\node_modules\express\lib\application.js:617:24)
3:29:34 PM web.1 |      at Object.<anonymous> (C:\Users\jdoyle\app.js:24:18)
3:29:34 PM web.1 |      at Module._compile (module.js:409:26)
3:29:34 PM web.1 |      at Object.Module._extensions..js (module.js:416:10)
3:29:34 PM web.1 |      at Module.load (module.js:343:32)
[DONE] Killing all processes with signal  null
3:29:34 PM web.1 Exited Abnormally
```

The only way to stop it and restart it is to open Task Manager and `End process` on all the instances of Node.

I thought Foreman ran all processes in the foreground? Why does my Node express server continue to run after `Ctrl + C` ?

If I run the web process by itself, without `grunt watch` I am able to kill the process with a simple `Ctrl + C`

**Comment by kaveet** [comment]
If anyone comes across this issue, the solution is to explicitly close the Express listener when `SIGINT` (Ctrl+C) is received.

Example:

```javascript
const app = express()
const listener = app.listen(...)

...

process.on('SIGINT', () => {
    listener.close(() => {
        process.exit(0)
    })
})
```
