### ISSUE TITLE
What happened to the npm package?

### ISSUE THREAD

**Issue by joeyespo** [strongloop/node-foreman#119]
I just tried:

```bash
$ npm install -g foreman
```

And got:

```bash
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/forman
```

Looks like [the package really is missing](https://www.npmjs.com/package/forman). Did it move?

**Comment by alemhnan** [comment]
You probably wrote `npm install -g forman` (misspelled foreman) instead of `npm install -g foreman`

**Comment by joeyespo** [comment]
Oh wow, you're right. Ha! Thanks for replying to something so obvious :sweat_smile:
