### ISSUE TITLE
Windows 10: 'foreman' is not recognized as an internal or external command...

### ISSUE THREAD

**Issue by xingped** [strongloop/node-foreman#134]
I installed foreman on windows 10 with npm install -g foreman, but when I try to run foreman, it can't be found (it is there). Other globally-installed packages are able to be executed just fine. Just not foreman.

When I try to do 'foreman run nodemon', the error is: "'foreman' is not recognized as an internal or external command, operable program or batch file".  Any ideas?

**Comment by dickeyxxx** [comment]
Read the readme. The command is `nf`.

**Comment by xingped** [comment]
Oh shit, I'm sorry. I skimmed right over that looking for anything windows-specific. First time I've switched to using node-forman from using the original ruby foreman. That's embarrassing. My bad.
