### ISSUE TITLE
Debug with new node debug feature

### ISSUE THREAD

**Issue by toovy** [strongloop/node-foreman#137]
Node has an experimental feature to enable [debugging with V8](https://nodejs.org/api/debugger.html). Trying it with `nf run` does not work:

    $ nf run node --inspect --debug-brk app.js
    error: unknown option `--inspect'

So the question is: Any ideas how to solve it?
Thanks in advance. BR toovy

**Comment by dickeyxxx** [comment]
Does it work without foreman?

**Comment by toovy** [comment]
This command works, starts the debugger, but my server won't start without the ENV vars set by node-foreman

    $ node --inspect --debug-brk app.js

**Comment by dickeyxxx** [comment]
run it like this `nf run node -- --inspect --debug-brk app.js`

**Comment by toovy** [comment]
@dickeyxxx great, that works fine! Thanks a lot.
