### ISSUE TITLE
How do people deal with dependencies for processes?

### ISSUE THREAD

**Issue by TylerBrock** [strongloop/node-foreman#138]
Lets say we have one Procfile entry (a) that depends on another (b) but (b) takes a long time to start. With node-foreman (a) sometimes fails because (b) isn't ready when (a) starts.

For example our web process (a) depends on the MongoDB process (b) being started.

The best thing I can think of (so far) is to add a wrapper shell script that starts (b) which sleeps for a bit before trying to start it, but this is pretty lame. What do other people do in this situation?

**Comment by nilskassube** [comment]
I would not start a database process with foreman, instead use the startup tools of your prefered Linux distribution. 

It's also possibly a good idea to re-connect to a database in an error handler in your Node.js app if the connection is dropped.

**Comment by TylerBrock** [comment]
We did what @nilskassube suggested.
