### ISSUE TITLE
.env Port variables not named PORT are not being used

### ISSUE THREAD

**Issue by ctsstc** [strongloop/node-foreman#145]
If I use `PORT` in `.env` like so it will use the port defined in the environment file.
```
PORT=7777
```

If I try to use something like `DB_PORT` it will default to 5000
```
DB_PORT=7777
```

I've looked through previous issues and I cannot tell if this is expected functionality or not. If it is, some added documentation about it would be helpful. Previously closed issues made it sound like the first example I gave should not work, yet it does.

If it's going to automatically assign the ports is there a way for me to access those in my scripts given that they're not matching what I threw into the `.env` file. (I guess I could pass it in as an argument to the script if supported, assume the same variable will contain the same port per line and not increment per read)

**Comment by ctsstc** [comment]
The above was run on Windows machine. I just ran it on my Mac and the environment variables are working fine as expected.

**Comment by AntJanus** [comment]
I'm on a windows machine and it ignores my PORT declaration altogether.
