### ISSUE TITLE
Unable to restart nodemon when started using `nf start`

### ISSUE THREAD

**Issue by SaitejaP** [strongloop/node-foreman#146]
my `npm start` script contains `babel index.js -o server.js && nodemon --optimize_for_size --max_old_space_size=920 --gc_interval=100 --harmony server.js`

nf executes the script and outputs the result. To restart the nodemon server, I typed `rs` and  I think its not passed to nodemon so nodemon could not restart the server. Is this intended or is there anything trivial that I am missing?

**Comment by rmg** [comment]
When you run `nodemon` directly it is giving you an interactive prompt, almost like a REPL, that you can give commands to.

When you run processes via `nf`, they are run in sub-shells with their inputs detached or closed and their outputs captured and decorated for multi-process logging.

When running multiple processes there would be no reasonable way to know which process should have stdin attached to `nf`'s stdin. :-(
