### ISSUE TITLE
Handling release entry in procfile

### ISSUE THREAD

**Issue by mkls** [strongloop/node-foreman#157]
Hello!

Heroku lets you define a ```release``` entry in the procfile, which will run only once when you release new a new version (good for db migrations for example) ([https://devcenter.heroku.com/articles/release-phase](https://devcenter.heroku.com/articles/release-phase)
)

If you have a release entry in your procfile which exits after finishing, node foreman will kill all other processes after this one exits.

If you have a procfile like this:
```
release: npm run migrate
web: node server/index.js
monitoring: node server/monitoring.js
```
if you do ```nf start``` it will run the migrate script and exit after.

Currently we work around this issue with specifying all other processes we want to run: 
```nf start web=1,monitoring=1```

One better solution would be if you could do ```nf start release=0```
An even better one if it could handle the special case of release entry.

If you let us know what is your take on this issue we will be happy to contribute with changes.

**Comment by mkls** [comment]
Any feedback on this?

**Comment by edmorley** [comment]
This would be useful

**Comment by mkls** [comment]
closing issues with stale bot does not seems to be a constructive way of resolving them...

**Comment by edmorley** [comment]
Please could this be reopened?
