### ISSUE TITLE
How to use different shell to /bin/sh

### ISSUE THREAD

**Issue by jacargentina** [strongloop/node-foreman#165]
I'm on macOS Catalina, and whishing to run my Profile on the zsh environment, as I've some things as automatic PATH for `node_modules/.bin` for example.

It seems `/bin/sh` is hardcoded and can't be customized?

**Comment by jacargentina** [comment]
@rmg is the package being actively maintained ?

**Comment by rmg** [comment]
Not actively, no. Sorry. 

As for the feature you're describing, `nf` is meant to run a `Procfile` in the same was as it would run on a PaaS like Heroku. It has been a while since I deployed an app that way so I'm not up to date; is this something other `Procfile` based tools now support?

**Comment by jacargentina** [comment]
@rmg i dont see other similar tools allow this. But can't node-foreman be the first one ? I can help in writing and testing it if u think it is feasible.
