### ISSUE TITLE
output bare console logs

### ISSUE THREAD

**Issue by pwmckenna** [strongloop/node-foreman#33]
Would it be possible the provide an option that would avoid appending timestamps and wrapping log lines?

**Comment by natevw** [comment]
+1 to improvements in this area. I'm happy with the prefixes/coloring, but hate how the lines are wrapped instead of just letting my terminal/logviewers handle it (especially when I change the terminal size and now the wrapping is stuck at the wrong column!)

**Comment by hunterloftis** [comment]
I would love to find a way to output within `nf` without truncating long lines. Makes debugging difficult.

**Comment by hunterloftis** [comment]
Scrap that, just found `-w`.

**Comment by samkelleher** [comment]
@hunterloftis  What's the `-w` flag to, can't find it documented anywhere?

**Comment by samkelleher** [comment]
@hunterloftis Scrap that, just found https://github.com/strongloop/node-foreman/blob/723d395e8173aec07e6c1d342896a6bdf52609bc/nf.js#L62


Just not mentioned anywhere in the detailed Readme.md
