### ISSUE TITLE
Double-quotes in environment variable values aren't handled well

### ISSUE THREAD

**Issue by tgs** [strongloop/node-foreman#45]
This happens with both JSON and KEY=VALUE format .env files.  My environment contains a JSON literal, a list of regular expressions to match against email addresses:

```
ACCESS_LIST='["^me@somewhere.com$"]'
```

In the JSON format, this would just be an array, rather than a string that contains a JSON array.

In either case, when writing `/etc/init/my-upstart-config-web-1.conf`, nf renders this variable as

```
env ACCESS_LIST="["^me@somewhere.com$"]"
```

This makes it very hard to get the right value through to my program - if I escape the inner quotes with backslashes, somehow the backslashes come through, while if I don't, then the inner quotes are omitted completely.  Ruby foreman renders this variable with surrounding single-quotes so that the inner double-quotes don't mess it up.

**Comment by gurdiga** [comment]
+1

**Comment by tgs** [comment]
I don't use nf anymore (switched to honcho), so I guess this limitation doesn't matter to me too much :man_shrugging:

**Comment by nmccready** [comment]
This should be re-opened its a valid problem.
