### ISSUE TITLE
Graceful shutdown?

### ISSUE THREAD

**Issue by hunterloftis** [strongloop/node-foreman#52]
Hey guys,

I'm considering node-foreman for our standard node tutorials on Heroku DevCenter, but I don't see anything here on graceful shutdowns. This is especially important for a lot of our customers who run worker processes.

What's the recommended way (if there is one?) of using node-foreman but allowing for graceful shutdowns locally when the user presses Cmd + C? If there isn't one, how would you feel about a PR?

Thanks!

**Comment by rmg** [comment]
@hunterloftis @dickeyxxx @ransombriggs is this still an issue? Or can it be closed?
