### ISSUE TITLE
Use an environment variable to determine which Procfile to use

### ISSUE THREAD

**Issue by joe-spanning** [strongloop/node-foreman#56]
If no Procfile exists in the root dir, and if not Procfile is defined via -f argument, it would be helpful if foreman checked an environment variable for which Procfile to use. This would allow our organization to easily define different Procfiles for dev, test, staging, etc.

**Comment by rmg** [comment]
@joe-spanning I'm doing some housekeeping and this issue is pretty old. Feel free to re-open if it is still something you care about.
