### ISSUE TITLE
'setuid argument must be a number or a string' when running in Docker

### ISSUE THREAD

**Issue by PavelVanecek** [strongloop/node-foreman#70]
How to reproduce:
- Run `nf start` in Docker

The line in question is this:
https://github.com/strongloop/node-foreman/blob/master/nf.js#L100
```
if(process.getuid && process.getuid() === 0) {
  process.setuid(process.env.SUDO_USER);
}
```

My guess is that this is caused by the SUDO_USER variable being not set because the application runs user root user. I tried to put `SUDO_USER=docker` to my `.env` file, but the issue persists. Is there a workaround?

**Comment by PavelVanecek** [comment]
Update: I am able to workaround. See my Dockerfile:

```
RUN adduser --disabled-password --gecos '' r
RUN mkdir -p /app && chown r:r /app
USER r
```

This however causes other issues. Is there a reason to call process.setuid?

**Comment by rmg** [comment]
@PavelVanecek the reason to call setuid is to drop the root privileges because they are only required to bind to port 80.

Other workarounds are:
 * Grant `CAP_NET_BIND_SERVICE` on the user that foreman is being run as (if on Linux)
 * Run a separate reverse proxy such as NGINX or Apache instead of using foreman's proxy
 * Create a firewall policy that redirects the port to your application port instead of using foreman's proxy

With all that said, there is a bug here that needs to be fixed. We need to add code to look up the uid of the username in `SUDO_USER` instead of passing the string.

**Comment by PavelVanecek** [comment]
That is a honorable reason. Maybe a check `if (process.env.SUDO_USER)` would be enough?

**Comment by rmg** [comment]
Looks like this is already being done slightly more correctly in proxy.js, but incorrectly in nf.js and forward.js :-(

**Comment by PavelVanecek** [comment]
https://www.npmjs.com/package/drop-sudo ?

**Comment by rmg** [comment]
@PavelVanecek that's basically what is already being done in proxy.js.. it should be moved to the run code, though, instead of the proxy and forward code.. I don't have time to do it now, but it would be an easy PR if you're willing.

**Comment by PavelVanecek** [comment]
@rmg That is where I got that code :) This PR is just a trivial fix, I don't have the confidence to deep dive.

**Comment by rmg** [comment]
As of #84 `nf` no longer does privilege dropping, so I'm closing this.

**Comment by rkmax** [comment]
@rmg Today I've installed 1.4.1 and got this error, any advice?
```
/src/node_modules/foreman/nf.js:100
       process.setuid(process.env.SUDO_USER);
```

**Comment by rmg** [comment]
@rkmax are you able to use `npm i -g foreman@next` instead? That will grab v2.0.0-1, which includes the above mentioned fix.

**Comment by rkmax** [comment]
Thanks @rmg

**Comment by kevinsimper** [comment]
@rkmax When is the next version released?

**Comment by rkmax** [comment]
@kevinsimper I think @rmg have a better idea than me

**Comment by rmg** [comment]
@kevinsimper @rkmax thank you for your patience. `foreman@2.0.0` has been released and is now the default version (aka, `latest`).
