### ISSUE TITLE
Preserve colorized output?

### ISSUE THREAD

**Issue by danawoodman** [strongloop/node-foreman#72]
Would it be possible for foreman to preserve colorized output? E.g. output from `console.log` using something like [chalk](https://github.com/sindresorhus/chalk)?

**Comment by Darkhogg** [comment]
It already does. The problem is probably due to stdin not being a terminal. Try forcing color output in chalk.

**Comment by dickeyxxx** [comment]
@rmg I think we can close this

**Comment by hai-cea** [comment]
This fixed it for me:
```
chalk.enabled = true;
```

**Comment by pioneerskies** [comment]
Here there is not a reference about how to troubleshoot nor resolve the issue. Trying with webpack output and I can't afford to keep it colorized. Should I open another issue for this?

**Comment by michaek** [comment]
Another way to achieve this would be to set the FORCE_COLOR environment variable, as described in the chalk documentation: https://github.com/chalk/chalk#chalksupportscolor Useful when a library you're consuming uses chalk.
