### ISSUE TITLE
Tests do not pass when using sed

### ISSUE THREAD

**Issue by jeffkole** [strongloop/node-foreman#81]
The default BSD `sed` installed on a Mac OSX 10.11 (El Capitan) does not support multiple `-e` arguments, so the `sed -i -e [...] -e [...]` commands in test scripts do not run successfully.  Installing `gnu-sed` solves the problem.

Would it be acceptable to change the scripts to fail loudly if `gsed` is not available, or invoke multiple `sed` commands to achieve the multiple substitutions?

**Comment by rmg** [comment]
Fixed by #109
