### ISSUE TITLE
Child processes do not receive stdin

### ISSUE THREAD

**Issue by zpnk** [strongloop/node-foreman#86]
Example Procfile:
```
web: nodemon app.js
watch: grunt watch:dev
```

Nodemon supports typing "rs" to manually trigger a restart. When running nodemon as a child process of node-foreman, it seems that this input is not passed along; a restart is not triggered.

The foreman gem does support this. Would it be feasible for node-foreman to?

Thanks!

**Comment by rmg** [comment]
@zpnk I can't think of a way to pick one that won't be wrong as often as it is right. Which process does stdin get sent to with `foreman`?

**Comment by zpnk** [comment]
@rmg Thanks for the reply. I can't speak to the workings of `foreman`, but in theory (and this may be a terrible idea) all child processes could receive stdin and then could operate on it as needed. 

My quick hack to get this working was to add the stdio option to child process [here](https://github.com/strongloop/node-foreman/blob/master/lib/proc.js#L26):
```js
var child = prog.spawn(file, args, {
  env: proc.env,
  stdio: ['inherit', 'pipe', 'pipe'] // stdin=inherit, stdout & stderr=pipe (default, so events work)
});
```

This allowed nodemon to pick up 'rs' and restart. However, I realized that restarting nodemon kicks off a new node process which is then not killed when `nf` is exited. I'm not sure how that kind of issue could be solved.

If there was a good way of going about that, perhaps something like `--inherit-stdin` could be useful?

The use-case of running nodemon+watch is pretty dev-specific though, so it's probably a better fit for grunt/gulp. 

Feel free to close, I don't want to litter your issues. :)
