### ISSUE TITLE
Support for multiple env files as in the original foreman

### ISSUE THREAD

**Issue by hlegendre** [strongloop/node-foreman#87]
Hi,

The original version of foreman allows for multiple env files passed at once as `--env file1,file2,...`.
Would it be possible to add this to node-foreman ?

Best regards.

Hugues.

**Comment by rmg** [comment]
Sounds like a reasonable feature to me. I don't have time to write it myself, but I would accept a PR that adds it :-)

**Comment by rmg** [comment]
Done in #77 and released in [v2.0.0-1](https://github.com/strongloop/node-foreman/releases/tag/v2.0.0-1), which can be installed using `npm -g i foreman@next` if you don't want to wait for the final release (no ETA, but testing would help).
