### ISSUE TITLE
Disable truncate feature

### ISSUE THREAD

**Issue by tylergraf** [strongloop/node-foreman#88]
I'd like to be able to disable the new truncate feature. Especially if I have some error that like to read the full output from.

Can I do that currently or would that be a feature request?

**Comment by samkelleher** [comment]
You can use the `-w` flag to disable trim. It's not mentioned in the readme, nor appears in the command usage for some reason - but it's there and works for me in 1.4.1

https://github.com/strongloop/node-foreman/blob/723d395e8173aec07e6c1d342896a6bdf52609bc/nf.js#L62

**Comment by tylergraf** [comment]
@samkelleher thank you thank you!
