### ISSUE TITLE
Cannot `nf start` with both `--wrap` and processes specified.

### ISSUE THREAD

**Issue by colllin** [strongloop/node-foreman#89]
Example of a command that doesn't do anything:

    nf start --wrap dev-server=1,dev-update-schema=1

Where both of these commands do something:

    nf start --wrap
    nf start dev-server=1,dev-update-schema=1

**Comment by colllin** [comment]
For the record, this also works:
    nf start --trim 1000 dev-server=1,dev-update-schema=1

**Comment by aseemk** [comment]
Running into this too.
