### ISSUE TITLE
Issues with Multiple Reverse Proxy

### ISSUE THREAD

**Issue by nazarhussain** [strongloop/node-foreman#93]
I am facing problem with multiple reverse proxies. It is not functioning as per described in Readme. 

I have following Procfile. 

```
app: node app.js | bunyan
api: node api.js | bunyan
```

Now I run it with: 

```
nf start -x 3000,4000 app=3,api=2
```

And the output that came out and cause error onward. 

```
[WARN] No ENV file found
[OKAY] Trimming display Output to 136 Columns
[OKAY] Starting Proxy Server [app] 3000 -> (5000-5002)
[OKAY] Starting Proxy Server [api] 3000 -> (5000-5001)
```

As you can see cleary there are two issues: 
1. It does not pick right port group for right process, only uses first that was specified
2. Second it uses same output port group for all jobs. 

It seems something is clearly broken. Please help me out to troubleshoot the issue. 

Thanks.

**Comment by nazarhussain** [comment]
Any one had looked into this issue?

**Comment by nazarhussain** [comment]
Just confirmed this bug is only in npm version `1.4.1` but is fixed in git repo. Please release the source code soon.

**Comment by rmg** [comment]
@nazarhussain you can install the pre-release that was published in November. It was tagged as `next` instead of `latest` so it isn't the default. Just do `npm install -g foreman@next` and you'll get most of the changes since 1.4.1.

**Comment by rmg** [comment]
I've just released [v2.0.0-1](https://github.com/strongloop/node-foreman/releases/tag/v2.0.0-1) as the `next` tag. @nazarhussain if you are able to try it out and confirm, it would help with preparing a 2.0.0 final release.

**Comment by nazarhussain** [comment]
@rmg will check it on Monday and let you know.

**Comment by nazarhussain** [comment]
@rmg Yes it works. Thanks for working on this issue. Here is node repo that contains minimal code to test this issue. https://github.com/nazarhussain/foreman-multi-proxy-test/
