### ISSUE TITLE
Disable trimming *and* wrapping?

### ISSUE THREAD

**Issue by aseemk** [strongloop/node-foreman#94]
Hi folks,

I'm a new user to node-foreman, but really excited by it. Thanks for all the great work!

Like others, I ran into the discovery that logs get trimmed (truncated) by default. Feedback: that feels like a particularly unfriendly default to me.

I studied the code and discovered `--wrap` (as noted in issue #88), but I ran into issue #89 where this doesn't seem to actually work for me.

I thought okay, I'll just set the trim to be really high (e.g. `--trim 99999999`). But it turns out even then, the code wraps to 500 chars by default — with no way to override this:

https://github.com/strongloop/node-foreman/blob/52e940117f569ebafcddc8d2a1fd41c1148dbbc0/lib/console.js#L40

https://github.com/strongloop/node-foreman/blob/52e940117f569ebafcddc8d2a1fd41c1148dbbc0/nf.js#L84-L93

A 500-char wrap might sound reasonable, but wrapping in general is often undesirable to me:

```
11:19:41 AM api.1 |  ... meta={"reqType":"priv
11:19:41 AM api.1 |  >  ate"} that was hard to read
11:19:41 AM api.1 |  ... https://some_lo
11:19:41 AM api.1 |  >  ng_url that I used to be able to cmd+double-click
```

As noted in issue https://github.com/strongloop/node-foreman/issues/33#issuecomment-74117284, wrapping feels unnecessary since the terminal already wraps natively (without breaking the log apart).

So I'd love a way to disable _both_ trimming and wrapping. Thank you!

**Comment by aseemk** [comment]
It'd also be nice in this case if there was no message logged (similar to issue #95).

**Comment by rmg** [comment]
I agree, trimming or wrapping by `nf` should probably be opt-in. If someone wants to submit a PR for it, I would definitely welcome it :-)

**Comment by aseemk** [comment]
Hey @rmg, thanks for your great PR! Just one thing: I notice that even with trimming disabled by default now (which is great), the code still _wraps_ to 500 chars by default — still with no way to override.

Default of 500:
https://github.com/strongloop/node-foreman/blob/760df083b63d7f3e10fb4fb5cc87895f23e40b18/lib/console.js#L45

No way to override:
https://github.com/strongloop/node-foreman/blob/760df083b63d7f3e10fb4fb5cc87895f23e40b18/nf.js#L90-L99

WDYT? If that sounds right to you too, can we re-open this issue?

As a user story, I simply want to not have node-foreman do any kind of wrapping or trimming or truncating of my logs at all! Just let my terminal wrap them naturally.

Thanks again!

**Comment by rmg** [comment]
I think the logging needs a lot of work in general. @aseemk if you are actually producing lines longer than 500 characters and they're getting mangled, then feel free to re-open. If it's not actually affecting your log output, then I'd prefer to just leave this closed since this will eventually be taken care of by refactoring the logger.
