### ISSUE TITLE
Silent option, at least for missing .env warning

### ISSUE THREAD

**Issue by aseemk** [strongloop/node-foreman#95]
We use node-foreman (as we used Foreman) without a `.env` file by default. Since this is expected for us, t'd be nice if we could suppress the warning:

https://github.com/FiftyThree/Studio/blob/a4a3be21d6fc4ece13f549d00c80815a7e4c16ec/node_modules/foreman/lib/envs.js#L124

This would be similar to `dotenv`'s `silent` option:

https://github.com/motdotla/dotenv#silent

Thanks!

**Comment by rmg** [comment]
@aseemk this sounds pretty reasonable to me. Any chance you'd be able to submit a pull request for it?

**Comment by rmg** [comment]
@aseemk would #115 be an acceptable solution for you?
