### ISSUE TITLE
Trimming clears output colorisation

### ISSUE THREAD

**Issue by fiznool** [strongloop/node-foreman#99]
I'm using winston to log messages to the console. When using the `--trim` option, if the line is trimmed, colors are lost.

See screenshot:

![screenshot from 2016-03-30 10-45-35](https://cloud.githubusercontent.com/assets/820863/14138356/b428c188-f664-11e5-8596-4112eac3495e.png)

Notice that the `info` text is colorised correctly in the first case, but not when `--trim` has trimmed the lines.

**Comment by dickeyxxx** [comment]
That's because winston disables the colors when it is not connected to a tty. This isn't an issue with node-foreman.

**Comment by fiznool** [comment]
Why does this only occur when the output is trimmed?  If Winston disables colours in non tty environments, I would have thought colours would be hidden in both scenarios above.

**Comment by dickeyxxx** [comment]
oh sorry! ignore my previous comment. I think this is why: https://github.com/strongloop/node-foreman/blob/master/lib/console.js#L27

Probably what needs to happen is to determine how long the string is sans-ascii-escapes and trim based on that.

**Comment by fiznool** [comment]
Yes that looks like the issue! If I get any time I'll try to put together a PR which solves this.
